spring:
  application:
    name: url-shortener

  datasource:
    username: postgres
    driver-class-name: org.postgresql.Driver
    # Local machine
    # url: jdbc:postgresql://localhost:5432/urlshortener
    # password: root1234
    # Docker
    url: jdbc:postgresql://localhost:5433/urlshortener
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # '[format_sql]': true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

server:
  port: 8080

app:
  base-url: http://localhost:8080
  short-code-length: 7
  default-expiry-days: 7
  # rate-limit:
  #   enabled: true
  #   requests-per-hour: 100
